/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yan_crash_core_NativeHandler */

#ifndef _Included_cn_yan_crash_core_NativeHandler
#define _Included_cn_yan_crash_core_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_yan_crash_core_NativeHandler
 * Method:    init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_yan_crash_core_NativeHandler_init
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
