/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_yan_crash_core_NativeHandler */

#ifndef _Included_cn_yan_crash_core_NativeHandler
#define _Included_cn_yan_crash_core_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_cn_yan_crash_core_NativeHandler_init
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL Java_cn_yan_crash_core_NativeHandler_crash
        (JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
